### ISSUE TITLE
Stakeholders and Personas

### ISSUE THREAD

**Issue by BacLuc** [ase-23-the-bald-owls/documentation#2]

**Comment by Off3line** [comment]
Persona 1: Markus , 45 . Long time Yu-Gi-Oh card fan. Goal: Wants to purchase his favorite card. Little to no experience (non-tech avy).

**Comment by haznai** [comment]
## Description of Stakeholders Task
> You should therefore provide a stakeholder analysis, listing primary (who uses the system directly), secondary (who provides input or receives the output of the system), tertiary (who is affected by your system but who, unlike the primary and secondary, never interacts directly with it) and facilitating stakeholders (who maintains, develops, or designs your solution). When describing the stakeholders, you should make an effort in describing why a certain group or individual is a member of a stakeholder group; these might also require making some early assumptions about certain features of your product.



## Sketch Answer (Final in latex document)

**Primary Stakeholders**
- Regular Customer: Wants to buy specific trading cards to round out their collection
- Subscribing Customers: Gets a box full of packs/boosters of cards each month. Packs and Boosters are a collection of random trading cards that have to be opened by the customer
- Retailers: Purchase trading cards in bulk to sell at their physical stores

**Secondary Stakeholders**
- Payment providers: Multiple payment options to encapsulate all possible customers
- Delivery providers: Good relationship is important as our business is making heavy use of specialized delivery services
- Customer Service Staff: Closely interlinked with the facilitating stakeholders role. Interact with the customers who have questions and inquiries about products

**Tertiary Stakeholders**
- Bookkeeping service: Maintaining the balances
- Competitors: Are interested in the prices and features of our stores
- Collectors: Use the shop to determine the value of their collection

**Facilitating Stakeholders**
- Influencers: Make the shop relevant in social media circles
- Developers: Maintain and develop features
- Rating staff: Have to rate cards based on condition, fill the products' description with information
- Distribution and Supply Chain managers: Manage the logistics behind the steady influx of new cards and packs

**Comment by haznai** [comment]
## Description of Persona Task: 

 You should include at least a persona for each category of stakeholder (4), although more are expected whenever a certain group might include more than one type of individual. When describing a persona this should be very detailed, especially with regards to goals of the project: you should provide: 
  - their background
  - job functions
  - current situation and challenges
  - and objectives and/or beliefs and/or anxieties 
  - you can omit to include a profile image.

## Sketch Answer (Final in latex document)

### Regular Customer (Primary Stakeholder)
#### Background
- David Müller, 26 years old
- Was a long-time fan of the trading card series, now sees the collecting of the cards as a nostalgic hobby
- Excited to talk and interact with the general Trading cards community

#### Job Functions
- Along with the subscribing customer, is the main income source for the shop
- Satisfaction with the shop is of utmost importance
- The main channel of spreading the word is good customer reviews for niche shops 

#### Current Situations and Challenges
- Early in their career, budget is moderate
- Competitors will also try to win the customer for themselves
- Concerned about the quality of the cards and if the rating of the cards is accurate
- Concerned about the authenticity of the purchased trading card 

#### Objectives and Beliefs
- Looks for the most competitive pricing on the market, but cares a lot about the quality of service as well
- Only authentic cards with quality are worth buying


### Customer Service Staff (Secondary Stakeholders)
#### Background
- Tania Zempo, 40 years old
- Experienced in Customer Service and Communication
- Works part-time and is resourceful with their time

#### Job Functions
- Answers questions and inquiries of customers
- Handles problems with delivery and product returns

#### Current Situations and Challenges
- Slow responses from other secondary stakeholders such as the delivery and payment providers make the job more difficult
- Works a limited number of days and cannot be present each day of the week

#### Objectives and Beliefs
- Clear communication from all the other stakeholders is a strong requirement she has for her job
- E-mailing and using customer service tools should be as smooth as possible
- Doesn't want to do duplicate work


### Competitors (Tertiary Stakeholders)
#### Background
- Stefan Schuber, 31 years old
- Passionate about trading cards and created his own, similiar, e-commerce shop
- Own e-commerce shop is established and employs 8 full-time employees 
- Has a personal stake in the online shop, but also cares about having the best shop for trading Yu-Gi-Oh! cards

#### Job Functions
- Founder of the competing shop, and therefore the main responsibility is the success of the shop
- Always on the lookout for competing online shops

#### Current Situations and Challenges
- Believes that other e-commerce stores will cut into the revenue of his shop
- Financial security is linked to the success of the shop

#### Objectives and Beliefs
- Cutting prices is not always possible because the employees have to be paid
- Adopting features of other competing e-commerce stores will lead to success of own store

### Developers (Facilitating Stakeholders)
#### Background
- Lena Gruber, 23 years old
- Frontend Junior Developer
- Passionate about Web Development and UI/UX design
- First big job in a company

#### Job Functions
- Maintains the entire frontend of the application
- Manages the marketing banners and information content of the site
- Takes part in sprints of envisioning possible features

#### Current Situations and Challenges
- Is knowledgeable in frontend development, but not experienced in startup development
- Complex technological setup could hinder productivity
- First job out of university means a longer onboarding phase

#### Objectives and Beliefs
- Excited to work for a startup and mixing in ideas for the product
- Using the latest tech-stack with third-party hosting providers will make her job the easiest
- Using a clear and succinct agile methodology allows easier integration and onboarding
